port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: true
mode: rule
log-level: warning
external-controller: 0.0.0.0:9090
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:1053
  enhanced-mode: redir-host #fake-ip
  nameserver:
    - 223.5.5.5
    - 119.29.29.29
  fallback:
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
tun:
  enable: true
  stack: system
proxies:
proxy-groups:
rules:
